### ISSUE TITLE
ReferenceError: Can't find variable: Rot13 (Edit: making InludeJS available as project.yaml setting)

### ISSUE THREAD

**Issue by kaspar-allenbach** [luke-nehemedia/craft-emailobfuscator#4]
I have a weird behaviour.

The obsfucated mail shows. But then suddenly this error appears in the console and the E-Mail adress is no longer shown:

> ReferenceError: Can't find variable: Rot13

The markup then renders like this:

```
<a
href="https://wetterfroscher.meteotest.review/buchen">registrieren Sie sich hier</a>. Die Registrierung dauert nur wenige Augenblicke.</p><p>Für Fragen und Anregungen schreiben Sie an folgende Adresse:<script type="text/javascript">Rot13.write('<n uers="znvygb:xbagnxg@jrggresebfpure.pu"> xbagnxg(ng)jrggresebfpure.pu</n>');</script><noscript><span
style="unicode-bidi:bidi-override;direction:rtl;">hc.rehcsorfrettew)ta(tkatnok < hc.rehcsorfrettew@tkatnok > </span></noscript></p></div></div></div><a
href="#mobileMenu" class="mmenuToggle"></a>
```
As you can see there is no longer a clickable part in the markup.

What to do about this???

- php 7.2.1.4
- craft 3.1.32.1
- craft-emailobfuscator 2.1.0

**Comment by kaspar-allenbach** [comment]
Further investigation. I tought it might be a scriptblocker like uBlock Origin.
But it happens on FF, Chrome & Safari without any extensions activated

https://wetterfroscher.meteotest.review/kontakt

**Comment by luke-nehemedia** [comment]
Hello

For some reason, the script file is not included in your site. 

Is the option "InludeJS" enabled in the settings?
With this setting enabled, the plugin should register the file in the `<head>` tag of your site.

**Comment by kaspar-allenbach** [comment]
Yep. That's the problem.

I use project.yaml to sync the cms structure.
Therfore I have `'allowAdminChanges' => false,` set on my LIVE system.

The downside is that I can't activate the EmailObfuscator on my LIVE system :(
Is it possible to write the lightswitch status into the project.yaml for a next version?

**Comment by luke-nehemedia** [comment]
I will definitely consider it, however, not in the next couple of weeks, since this is a free plugin and I deploy it in my free time. 

However, implementing support for project config seems reasonable, but involves quite some changes and testing. Therefore I am not able to do it short-term right now.

**Comment by kaspar-allenbach** [comment]
No hurry. It's a free plugin after all.

Besser den Sommer geniessen ☀️

**Comment by kaspar-allenbach** [comment]
hmm. nope, the lightswitch is activated. Still does not include the script
