### ISSUE TITLE
propaganistas/email-obfuscator is not on packagist anymore

### ISSUE THREAD

**Issue by krizzzly** [luke-nehemedia/craft-emailobfuscator#6]
Hello,

your package is relying on: "propaganistas/email-obfuscator": "~1.0"
Unfortunately this package doesnt exist anymore.

https://packagist.org/packages/propaganistas/email-obfuscator

**Comment by luke-nehemedia** [comment]
Hello krizzzly,

I will take care of that soon. Right now I do not have the time because of my studies but I will update the plugin accordingly as soon as possible.

**Comment by romainpoirier** [comment]
Any update on this issue? I'm new here and still can't install the plugin for the same reason.

```
Package operations: 2 installs, 0 updates, 0 removals
  - Installing propaganistas/email-obfuscator (1.0.7): Downloading (failed)    Failed to download propaganistas/email-obfuscator from dist: The "https://api.github.com/repos/Propaganistas/Email-Obfuscator/zipball/76160733eefb7a73f7277fea4b2d093922e551b5" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing propaganistas/email-obfuscator (1.0.7): Cloning 76160733ee

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Failed to clone https://github.com/Propaganistas/Email-Obfuscator.git via https, ssh protocols, aborting.

  - https://github.com/Propaganistas/Email-Obfuscator.git
    Cloning into '/vendor/propaganistas/email-obfuscator'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/Propaganistas/Email-Obfuscator.git/'

  - git@github.com:Propaganistas/Email-Obfuscator.git
    Cloning into '/vendor/propaganistas/email-obfuscator'...
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```

**Comment by dsite** [comment]
I'm also affected by this issue. Before I refactor with another plugin, I thought I'd check in here first. 

Is this something that you will be able to fix? Or does the disappearance of the Propaganistas package make that impossible?

Thanks and have a nice day.

**Comment by luke-nehemedia** [comment]
Hello

I am planning to release an update the following 14 days. Hopefully this week. 
I will definitely fix the issue with the packagist package, and might add support for siteconfig.

**Comment by luke-nehemedia** [comment]
I fixed this one. Sorry for the long delay. I hope it works now.
