### ISSUE TITLE
Plugin not up to date in the Plugin Store

### ISSUE THREAD

**Issue by olivierbon** [luke-nehemedia/craft-emailobfuscator#8]
It seems that your latest release (`2.2.0`) is not [on the Plugin Store](https://plugins.craftcms.com/craft-emailobfuscator).

Can you check in your Craft ID and make sure your GitHub account is connected?

**Comment by luke-nehemedia** [comment]
I have check it and also released a new update today. 
I will contact the support if it will not appear within 24h.
